version: '2'
services:

  celery:
    container_name: pmp-celery
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    volumes:
      - pmp-celery-logging:/usr/src/app/logging

volumes:
  pmp-celery-logging:
