version: '2'
services:

  django:
    container_name: pmp-django
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DJANGO_SYS_EMAIL
      - DJANGO_SYS_EMAIL_PWD
      - MODE
    build:
      context: .
    networks:
      - pmp-django-nginx
    volumes:
      - pmp-django-static:/usr/src/app/static
      - pmp-django-logging:/usr/src/app/logging
    ports:
      - 8000:8000

  nginx:
    container_name: pmp-nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    networks:
      - pmp-django-nginx
    volumes:
      - pmp-django-static:/usr/src/app/static
      - pmp-nginx-cert:/etc/ssl/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django

volumes:
  pmp-django-static:
  pmp-nginx-cert:
  pmp-django-logging:

networks:
  pmp-django-nginx:
    driver: bridge
