# Generated by Django 2.1.3 on 2019-11-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth1Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('oauth_token', models.CharField(max_length=200)),
                ('oauth_token_secret', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OAuth1Tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2CodeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OAuth2CodeRequests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('token_type', models.CharField(max_length=20)),
                ('access_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(max_length=200)),
                ('expires_at', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OAuth2Tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mode', models.CharField(max_length=60)),
                ('open_status', models.CharField(max_length=60)),
                ('grace_period', models.FloatField()),
                ('work_hours', jsonfield.fields.JSONField()),
                ('vacation_days', jsonfield.fields.JSONField()),
                ('velocities', jsonfield.fields.JSONField(null=True)),
                ('project_settings', jsonfield.fields.JSONField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60, null=True)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(null=True)),
                ('type', models.CharField(choices=[('JI', 'JIRA')], max_length=20)),
                ('connectivity_status', jsonfield.fields.JSONField(null=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('params', jsonfield.fields.JSONField(null=True)),
                ('oauth2_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etabotapp.OAuth2Token')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TMSAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_tms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etabotapp.TMS'),
        ),
    ]
