# Generated by Django 2.1.3 on 2019-11-27 12:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etabotapp', '0002_auto_20191111_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vacation_days',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='velocities',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='tms',
            name='connectivity_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tms',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
