# Generated by Django 2.2.19 on 2021-03-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etabotapp', '0003_auto_20191127_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('CN', 'Canceled'), ('DN', 'Done'), ('FL', 'Failed'), ('X', 'Other')], max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celeryTasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
