# Generated by Django 2.2.19 on 2021-04-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabotapp', '0006_auto_20210325_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
